package jmn.iot.model;

public enum Topic {
    LIVING_ROOM_LIGHT,
    LIVING_ROOM_FAN,
    LIVING_ROOM_LIGHT_SENSOR,
    LIVING_ROOM_MOTION_SENSOR,
    LIVING_ROOM_TEMPERATURE_SENSOR,

    BEDROOM_LIGHT,
    BEDROOM_FAN,
    BEDROOM_ALARM,

    HOUSE_TEMPERATURE,
    HOUSE_HUMIDITY
}
